# Number of days of inactivity before an issue becomes stale
daysUntilStale: 3
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Denne PR-en har automatisk blitt markert som inaktiv fordi den ikke har hatt noen nylig aktivitet.
  Den vil bli lukket hvis det ikke blir foretatt noe mer aktivitet innen 7 dager.
  Takk for at du får saken din igjennom!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Denne PR-en har nå blitt lukket pga. inaktivitet. Du kan fortsatt reåpne den.
