apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: tiltaksgjennomforing-api-alert
  namespace: default
  labels:
    team: teamtag
spec:
  receivers:
    slack:
      channel: 'arbeidsgiver-notifications'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: up{app="tiltaksgjennomforing-api", job="kubernetes-pods"} == 0
      for: 2m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
