apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tiltaksgjennomforing-api:latest
  team: teamtag
  port: 8080
  liveness:
    path: /tiltaksgjennomforing-api/internal/actuator/info
    initialDelay: 20
  readiness:
    path: /tiltaksgjennomforing-api/internal/actuator/info
    initialDelay: 20
  ingresses:
  - https://arbeidsgiver.nais.preprod.local/tiltaksgjennomforing-api/
  vault:
    enabled: true
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: preprod
  webproxy: true
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus