apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tiltaksgjennomforing-api:{{version}}
  team: teamtag
  port: 8080
  liveness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 50
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 800Mi
    requests:
      cpu: 400m
      memory: 400Mi
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring-profil}}
  webproxy: true
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus