apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-backend
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tiltaksgjennomforing-backend:latest
  team: teamtag
  port: 8080
  secrets: true
  ingresses:
  - https://tjenester-t1.nav.no/tiltaksgjennomforing
  liveness:
    path: /tiltaksgjennomforing/internal/isAlive
    initialDelay: 20
  readiness:
    path: /tiltaksgjennomforing/internal/isReady
    initialDelay: 20
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: nais
  - name: CONTEXT_PATH
    value: /tiltaksgjennomforing