apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tiltaksgjennomforing-api:{{version}}
  team: teamtag
  port: 8080
  liveness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 80
  readiness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 80
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring-profil}}
  webproxy: true
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus