apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  liveness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring-profil}}
  webproxy: true
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus