spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://b27dbvl026.preprod.local:5432/tiltaksgjennomforing-p15-q0'
  sql:
    init:
      platform: postgres

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: https://tiltak-fakelogin.ekstern.dev.nav.no/metadata?issuer=aad
      accepted_audience: fake-aad
    tokenx:
      discoveryurl: https://tiltak-fakelogin.ekstern.dev.nav.no/metadata?issuer=tokenx
      accepted_audience: fake-tokenx

tiltaksgjennomforing:
  database:
    database-navn: tiltaksgjennomforing-p15-q0
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 8
    max-lifetime: 300000
  kontoregister:
    fake: true
  beslutter-ad-gruppe:
    id: 1a1d2745-952f-4a0f-839f-9530145b1d4a
  kafka:
    enabled: true
    fake-url: http://tiltak-refusjon-api-labs/fake-kafka
  altinn-tilgangsstyring:
    uri: http://tiltaksgjennomforing-wiremock-q0/altinn-tilgangsstyring
    proxyUri: http://heh:9090/
    beOmRettighetBaseUrl: https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    ltsMidlertidigServiceCode: 5516
    ltsMidlertidigServiceEdition: 1
    ltsVarigServiceCode: 5516
    ltsVarigServiceEdition: 2
    sommerjobbServiceCode: 5516
    sommerjobbServiceEdition: 3
    mentorServiceCode: 5516
    mentorServiceEdition: 4
    inkluderingstilskuddServiceCode: 5516
    inkluderingstilskuddServiceEdition: 5
    arbtreningServiceCode: 5332
    arbtreningServiceEdition: 1
    vtaoServiceCode: 5516
    vtaoServiceEdition: 5 # TODO: Finn riktig service edition
    vtaoAktiv: true
    altinnApiKey: foo
    apiGwApiKey: foo
  ereg:
    uri: http://tiltaksgjennomforing-wiremock-q0/ereg
  sts:
    username: foo
    password: bar
    rest-uri: http://tiltaksgjennomforing-wiremock-q0/sts/sts/token
  axsys:
    uri: http://tiltaksgjennomforing-wiremock-q0/axsys
  oppgave:
    oppgave-uri: http://tiltaksgjennomforing-wiremock-q0/api/v1/oppgaver
  veilarboppfolging:
    url: http://tiltaksgjennomforing-wiremock-q0
  norg2:
    geografisk:
      url: http://tiltaksgjennomforing-wiremock-q0/norg2/api/v1/enhet/navkontor/
    enhet:
      url: http://tiltaksgjennomforing-wiremock-q0/norg2/api/v1/enhet/
  consumer:
    system:
      id: testsystem
  persondata:
    uri: http://tiltaksgjennomforing-wiremock-q0/persondata
  dokgen:
    uri: http://tiltak-dokgen/template/tiltak-avtale/create-pdf
  notifikasjoner:
    uri: https://notifikasjon-fake-produsent-api.labs.nais.io/api/graphql
    lenke: https://arbeidsgiver.labs.nais.io/tiltaksgjennomforing/avtale/
    enabled: false
  tilskuddsperioder:
    tiltakstyper: SOMMERJOBB, MIDLERTIDIG_LONNSTILSKUDD, VARIG_LONNSTILSKUDD
  arena:
    kafka:
      tiltakdeltaker-endret-topic: 'teamarenanais.aapen-arena-tiltakdeltakerendret-v1-q1'
      tiltakgjennomforing-endret-topic: 'teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-q1'
    ords:
      url: http://tiltaksgjennomforing-wiremock-q0/arena-ords
      client-id: client
      client-secret: secret
    aktivitet-acl:
      url: http://tiltaksgjennomforing-wiremock-q0/aktivitet-arena-acl

ELECTOR_PATH: null
