server.servlet.context-path: /tiltaksgjennomforing-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  application:
    name: tiltaksgjennomforing-api
  main:
    banner-mode: "off"
  jmx:
    enabled: false
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#TODO: Feil pakke: Flytt Kafka avien verdier her under tiltaksgjennomforing.kafka
no.nav.gcp.kafka.aiven:
  bootstrap-servers: ${KAFKA_BROKERS}
  truststore-path: ${KAFKA_TRUSTSTORE_PATH}
  truststore-password: ${KAFKA_CREDSTORE_PASSWORD}
  keystore-path: ${KAFKA_KEYSTORE_PATH}
  keystore-password: ${KAFKA_CREDSTORE_PASSWORD}
  schema-registry-url: ${KAFKA_SCHEMA_REGISTRY}
  schema-registry-credentials-source: USER_INFO
  schema-registry-user-info: "${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}"
  security-protocol: SSL

tiltaksgjennomforing:
  beslutter-ad-gruppe:
    id: ${beslutter.ad.gruppe}
  kafka:
    enabled: true
  persondata:
    uri: http://pdl-api.default.svc.nais.local/graphql
  dokgen:
    uri: http://tiltak-dokgen.arbeidsgiver.svc.nais.local/template/tiltak-avtale/create-pdf
  dvh-melding:
    feature-enabled: false
    fixed-delay: 600000
  tilskuddsperioder:
    tiltakstyper: SOMMERJOBB