spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver

no.nav.security.oidc:
  issuers: selvbetjening, isso, system
  issuer:
    selvbetjening:
      discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
      accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
    isso:
      discoveryurl: https://login.microsoftonline.com/NAVQ.onmicrosoft.com/.well-known/openid-configuration
      accepted_audience: 38e07d31-659d-4595-939a-f18dce3446c5
    system:
      discoveryurl: http://security-token-service.default.svc.nais.local/rest/v1/sts/.well-known/openid-configuration
      accepted_audience: ${tiltaksgjennomforing.audience.system}

tiltaksgjennomforing:
  database:
    database-navn: tiltaksgjennomforing-preprod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 2
    max-lifetime: 300000
  altinn:
    altinn-uri: https://api-gw-q1.adeo.no
  ereg:
    ereg-uri: https://modapp-q1.adeo.no
  axsys:
    axsys-uri: https://axsys.nais.preprod.local
    nav-consumer-id: ${tiltaksgjennomforing.serviceuser.username}
  consumer:
    system:
      id: ${tiltaksgjennomforing.consumer.system}

http:
  proxy:
    parametername: nothing