spring:
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    banner-mode: "console"
  kafka:
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}
    producer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}

no.nav.security.oidc:
  issuers: selvbetjening, isso
  issuer:
    selvbetjening:
      discoveryurl: http://metadata-selvbetjening
      accepted_audience: aud-selvbetjening
    isso:
      discoveryurl: http://metadata-isso
      accepted_audience: aud-isso

tiltaksgjennomforing:
  altinn-tilgangsstyring:
    uri: http://localhost:8090
    altinn-api-key: test
    api-gw-api-key: test
    service-code: 42
    service-edition: 1
  altinn-varsel:
    uri: https://tt02.altinn.no/ServiceEngineExternal/NotificationAgencyExternalBasic.svc
  ereg:
    ereg-uri: http://localhost:8090  axsys:
    axsys-uri: http://localhost:8090