server.servlet.context-path: /tiltaksgjennomforing-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
  task:
    scheduling.pool.size: 8
  cache:
    type: caffeine
  jpa:
    open-in-view: true
  application:
    name: tiltaksgjennomforing-api
  main:
    banner-mode: "off"
  jmx:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    security:
      protocol: SSL
    ssl:
      trust-store-type: JKS
      trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
      trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}
      key-store-type: PKCS12
      key-store-location: file:${KAFKA_KEYSTORE_PATH}
      key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        ssl.endpoint.identification.algorithm: ""
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${spring.application.name}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      basic.auth:
        credentials.source: USER_INFO
        user.info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}

tiltaksgjennomforing:
  retry: # Delay i millisekunder mellom hver retry
    delay: 1000
    max-delay: 20000
  kafka:
    enabled: true
  dokgen:
    uri: http://tiltak-dokgen.arbeidsgiver.svc.nais.local/template/tiltak-avtale/create-pdf
  notifikasjoner:
    uri: https://ag-notifikasjon-produsent-api.dev.intern.nav.no/api/graphql
    lenke: https://arbeidsgiver.nav.no/tiltaksgjennomforing/avtale/

no.nav.security.jwt:
  client:
    registration:
      aad-graph:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      aad:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      aad-anonym:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

caches:
  caffeine:
    - name: pdl_cache
      expiryInMinutes: 60
      maximumSize: 1000
    - name: norgnavn_cache
      expiryInMinutes: 60
      maximumSize: 1000
    - name: norggeoenhet_cache
      expiryInMinutes: 60
      maximumSize: 1000
    - name: veilarboppfolging_cache
      expiryInMinutes: 5
      maximumSize: 1000
    - name: axsys_cache
      expiryInMinutes: 60
      maximumSize: 1000
