server.servlet.context-path: /tiltaksgjennomforing-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  main:
    banner-mode: "off"
  datasource:
    hikari:
      maximum-pool-size: 2