spring:
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    banner-mode: "console"

no.nav.security.oidc:
  issuers: selvbetjening, isso
  issuer:
    selvbetjening:
      discoveryurl: http://tiltak-fakelogin/metadata?issuer=selvbetjening
      accepted_audience: aud-selvbetjening
    isso:
      discoveryurl: http://tiltak-fakelogin/metadata?issuer=isso
      accepted_audience: aud-isso
    
tiltaksgjennomforing:
  beslutter-ad-gruppe:
    id: 1a1d2745-952f-4a0f-839f-9530145b1d4a
  kafka:
    enabled: false
    fake: true
    fake-url: http://tiltak-refusjon-api/fake-kafka
  altinn-tilgangsstyring:
    uri: http://tiltaksgjennomforing-wiremock/altinn-tilgangsstyring
    proxyUri: http://heh:9090/
    beOmRettighetBaseUrl: https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    ltsMidlertidigServiceCode: 5516
    ltsMidlertidigServiceEdition: 1
    ltsVarigServiceCode: 5516
    ltsVarigServiceEdition: 2
    arbtreningServiceCode: 5332
    arbtreningServiceEdition: 1
    altinnApiKey: foo
    apiGwApiKey: foo
  ereg:
    uri: http://tiltaksgjennomforing-wiremock/ereg
  sts:
    username: foo
    password: bar
    rest-uri: http://tiltaksgjennomforing-wiremock/sts/sts/token
  axsys:
    uri: http://tiltaksgjennomforing-wiremock/axsys
  abac:
    veilarbabac-uri: http://tiltaksgjennomforing-wiremock/veilarbabac
  oppgave:
    oppgave-uri: http://tiltaksgjennomforing-wiremock/api/v1/oppgaver
  veilarbarena:
    url: http://tiltaksgjennomforing-wiremock/veilarbarena/oppfolgingsstatus
  norg2:
    url: http://tiltaksgjennomforing-wiremock/norg2/api/v1/enhet/navkontor/
  consumer:
    system:
      id: testsystem
  persondata:
    uri: http://tiltaksgjennomforing-wiremock/persondata
  unleash:
    mock: true