spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://A01DBVL033.adeo.no:5432/tiltaksgjennomforing-p15-prod'

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
    system:
      discoveryurl: http://security-token-service.default.svc.nais.local/rest/v1/sts/.well-known/openid-configuration
      accepted_audience: ${tiltaksgjennomforing.audience.system}
    azure-access-token:
      discoveryurl: "https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/.well-known/openid-configuration"
      accepted_audience: "https://management.core.windows.net/"
  client:
    registration:
      ag-notifikasjon-produsent-api:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-gcp.fager.notifikasjon-produsent-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      sokos-kontoregister:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-fss.okonomi.sokos-kontoregister/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      veilarboppfolging:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-gcp.poao.veilarboppfolging/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      poao-tilgang:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-fss.poao.poao-tilgang/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-api:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-fss.pdl.pdl-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      tokenx-altinn:
        token-endpoint-url: ${TOKEN_X_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-jwk: /var/run/secrets/nais.io/jwker/TOKEN_X_PRIVATE_JWK
          client-auth-method: private_key_jwt
        token-exchange:
          audience: prod-gcp:arbeidsgiver:altinn-rettigheter-proxy
      oppgave:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-fss.oppgavehandtering.oppgave/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      aktivitet-arena-acl:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-gcp.dab.aktivitet-arena-acl/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      tiltak-hendelse-aktivitetsplan:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-gcp.team-tiltak.tiltak-hendelse-aktivitetsplan/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

tiltaksgjennomforing:
  persondata:
    uri: https://pdl-api.intern.nav.no/graphql
  kontoregister:
    uri: https://sokos-kontoregister.nais.adeo.no/kontoregister/api/v1/hent-kontonummer-for-organisasjon/
    consumerId: ${tiltaksgjennomforing.serviceuser.username}
    azureConfig: true
    realClient: true
  ad-grupper:
    beslutter: 156f4f79-6909-4be1-8045-323f55590898
    fortrolig-adresse: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    strengt-fortrolig-adresse: ad7b87a6-9180-467c-affc-20a566b0fec0
  database:
    database-navn: tiltaksgjennomforing-p15-prod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/prod-fss
    minimum-idle: 1
    maximum-pool-size: 8
    max-lifetime: 300000
  altinn-tilgangsstyring:
    uri: https://api-gw.adeo.no/
    proxyUri: https://altinn-rettigheter-proxy.intern.nav.no/altinn-rettigheter-proxy/
    beOmRettighetBaseUrl: https://arbeidsgiver.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    sommerjobbServiceCode: 5516
    sommerjobbServiceEdition: 3
    ltsMidlertidigServiceCode: 5516
    ltsMidlertidigServiceEdition: 1
    ltsVarigServiceCode: 5516
    ltsVarigServiceEdition: 2
    arbtreningServiceCode: 5332
    arbtreningServiceEdition: 2
    mentorServiceCode: 5516
    mentorServiceEdition: 4
    inkluderingstilskuddServiceCode: 5516
    inkluderingstilskuddServiceEdition: 5
    vtaoServiceCode: 5516
    vtaoServiceEdition: 5 # TODO: Finn riktig service edition

  ereg:
    uri: https://ereg-services.intern.nav.no/api/v2/organisasjon
  sts:
    username: ${tiltaksgjennomforing.serviceuser.username}
    password: ${tiltaksgjennomforing.serviceuser.password}
    rest-uri: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
  axsys:
    uri: https://axsys.nais.adeo.no/api/v1/tilgang
    nav-consumer-id: ${tiltaksgjennomforing.serviceuser.username}
  oppgave:
    oppgave-uri: https://oppgave.nais.adeo.no/api/v1/oppgaver
  unleash:
    enabled: true
    api-uri: ${UNLEASH_SERVER_API_URL}/api
    api-token: ${UNLEASH_SERVER_API_TOKEN}
  consumer:
    system:
      id: ${tiltaksgjennomforing.consumer.system}
  veilarboppfolging:
    url: https://veilarboppfolging-gcp.intern.nav.no
  poao-tilgang:
    url: http://poao-tilgang.poao.svc.nais.local
  norg2:
    geografisk:
      url: https://norg2.nais.adeo.no/norg2/api/v1/enhet/navkontor/
    enhet:
      url: https://norg2.nais.adeo.no/norg2/api/v1/enhet/
  notifikasjoner:
    uri: https://ag-notifikasjon-produsent-api.intern.nav.no/api/graphql
    lenke: https://arbeidsgiver.nav.no/tiltaksgjennomforing/avtale/
    enabled: true
  arena:
    kafka:
      tiltakdeltaker-endret-topic: 'teamarenanais.aapen-arena-tiltakdeltakerendret-v1-p'
      tiltakgjennomforing-endret-topic: 'teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-p'
    ords:
      url: https://arena-ords.nais.adeo.no
      client-id: ${ARENA_ORDS_CLIENT_ID}
      client-secret: ${ARENA_ORDS_CLIENT_SECRET}
    aktivitet-acl:
      url: https://aktivitet-arena-acl.intern.nav.no
    hendelse-aktivitetsplan:
      url: https://tiltak-hendelse-aktivitetsplan.intern.nav.no
