spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://b27dbvl032.preprod.local:5432/tiltaksgjennomforing-p15-preprod'
  sql:
    init:
      platform: postgres

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
    system:
      discoveryurl: http://security-token-service.default.svc.nais.local/rest/v1/sts/.well-known/openid-configuration
      accepted_audience: ${tiltaksgjennomforing.audience.system}
  client:
    registration:
      ag-notifikasjon-produsent-api:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-gcp.fager.notifikasjon-produsent-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      sokos-kontoregister:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-fss.okonomi.sokos-kontoregister-q2/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      veilarbarena:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-fss.pto.veilarbarena/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      poao-tilgang:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-fss.poao.poao-tilgang/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-api:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-fss.pdl.pdl-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      tokenx-altinn:
        token-endpoint-url: ${TOKEN_X_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-jwk: /var/run/secrets/nais.io/jwker/TOKEN_X_PRIVATE_JWK
          client-auth-method: private_key_jwt
        token-exchange:
          audience: dev-gcp:arbeidsgiver:altinn-rettigheter-proxy
      oppgave:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-fss.oppgavehandtering.oppgave-q1/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

tiltaksgjennomforing:
  persondata:
    uri: https://pdl-api.dev.intern.nav.no/graphql
  kontoregister:
    uri: https://sokos-kontoregister-q2.dev.adeo.no/kontoregister/api/v1/hent-kontonummer-for-organisasjon/
    consumerId: ${tiltaksgjennomforing.serviceuser.username}
    azureConfig: true
    realClient: true
  database:
    database-navn: tiltaksgjennomforing-p15-preprod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 8
    max-lifetime: 300000
  altinn-tilgangsstyring:
    uri: https://api-gw-q1.adeo.no
    proxyUri: https://altinn-rettigheter-proxy.intern.dev.nav.no/altinn-rettigheter-proxy
    beOmRettighetBaseUrl: https://min-side-arbeidsgiver.dev.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    ltsMidlertidigServiceCode: 5516
    ltsMidlertidigServiceEdition: 1
    ltsVarigServiceCode: 5516
    ltsVarigServiceEdition: 2
    sommerjobbServiceCode: 5516
    sommerjobbServiceEdition: 3
    mentorServiceCode: 5516
    mentorServiceEdition: 4
    inkluderingstilskuddServiceCode: 5516
    inkluderingstilskuddServiceEdition: 5
    arbtreningServiceCode: 5332
    arbtreningServiceEdition: 1
    vtaoServiceCode: 5516
    vtaoServiceEdition: 5 # TODO: Finn riktig service edition
    vtaoAktiv: true
  ereg:
    uri: https://ereg-services-q1.dev.intern.nav.no/api/v2/organisasjon
  sts:
    username: ${tiltaksgjennomforing.serviceuser.username}
    password: ${tiltaksgjennomforing.serviceuser.password}
    rest-uri: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
  axsys:
    uri: https://axsys.nais.preprod.local/api/v1/tilgang
    nav-consumer-id: ${tiltaksgjennomforing.serviceuser.username}
  oppgave:
    oppgave-uri: https://oppgave.nais.preprod.local/api/v1/oppgaver
  unleash:
    enabled: true
    api-uri: ${UNLEASH_SERVER_API_URL}/api
    api-token: ${UNLEASH_SERVER_API_TOKEN}
  consumer:
    system:
      id: ${tiltaksgjennomforing.consumer.system}
  veilarbarena:
    url: https://veilarbarena.dev.intern.nav.no/veilarbarena/api/arena/status
    nav-consumer-id: ${tiltaksgjennomforing.serviceuser.username}
  poao-tilgang:
    url: http://poao-tilgang.poao.svc.nais.local
  norg2:
    geografisk:
      url: https://app-q1.adeo.no/norg2/api/v1/enhet/navkontor/
    enhet:
      url: https://app-q1.adeo.no/norg2/api/v1/enhet/
  notifikasjoner:
    uri: https://ag-notifikasjon-produsent-api.intern.dev.nav.no/api/graphql
    lenke: https://tiltaksgjennomforing.ekstern.dev.nav.no/tiltaksgjennomforing/avtale/
    enabled: true
  dvh-melding:
    gruppe-tilgang: ${beslutter.ad.gruppe}
  utvikler-tilgang:
    gruppe-tilgang: ${beslutter.ad.gruppe}
  arena:
    kafka:
      tiltakdeltaker-endret-topic: 'teamarenanais.aapen-arena-tiltakdeltakerendret-v1-q2'
      tiltakgjennomforing-endret-topic: 'teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-q2'
      tiltakssak-endret-topic: 'teamarenanais.aapen-arena-tiltakssakendret-v1-q2'
    ords:
      url: https://arena-ords-q2.nais.preprod.local
      client-id: ${ARENA_ORDS_CLIENT_ID}
      client-secret: ${ARENA_ORDS_CLIENT_SECRET}
