spring:
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    banner-mode: "console"

no.nav.security.oidc:
  issuers: selvbetjening, isso
  issuer:
    selvbetjening:
      discoveryurl: http://tiltak-fakelogin/metadata?issuer=selvbetjening
      accepted_audience: aud-selvbetjening
    isso:
      discoveryurl: http://tiltak-fakelogin/metadata?issuer=isso
      accepted_audience: aud-isso
    
tiltaksgjennomforing:
  kafka:
    enabled: false
  altinn-tilgangsstyring:
    uri: http://tiltaksgjennomforing-wiremock/altinn-tilgangsstyring
    proxyUri: http://tiltaksgjennomforing-wiremock/altinn-rettigheter-proxy/ekstern/altinn/api/serviceowner/reportees
    lts-midlertidig-service-code: 5516
    lts-midlertidig-service-edition: 1
    lts-varig-service-code: 5516
    lts-varig-service-edition: 2
    arbtrening-service-code: 5332
    arbtrening-service-edition: 1
  ereg:
    uri: http://tiltaksgjennomforing-wiremock/ereg
  sts:
    username: foo
    password: bar
    rest-uri: http://tiltaksgjennomforing-wiremock/sts/sts/token
  axsys:
    uri: http://tiltaksgjennomforing-wiremock/axsys
  abac:
    veilarbabac-uri: http://tiltaksgjennomforing-wiremock/veilarbabac
  consumer:
    system:
      id: testsystem
  persondata:
    uri: http://tiltaksgjennomforing-wiremock/persondata
