server.servlet.context-path: /tiltaksgjennomforing-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  main:
    banner-mode: "off"
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      max-lifetime: 300000
