server.servlet.context-path: /tiltaksgjennomforing-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  application:
    name: tiltaksgjennomforing-api
  profiles:
    active: dev
  main:
    banner-mode: "off"
