spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  kafka:
    bootstrap-servers: b27apvl00045.preprod.local:8443, b27apvl00046.preprod.local:8443, b27apvl00047.preprod.local:8443
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${tiltaksgjennomforing.serviceuser.username}" password="${tiltaksgjennomforing.serviceuser.password}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}

no.nav.security.jwt:
  issuer:
    selvbetjening:
      discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
      accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
      cookie_name: selvbetjening-idtoken
    isso:
      discoveryurl: https://login.microsoftonline.com/NAVQ.onmicrosoft.com/.well-known/openid-configuration
      accepted_audience: 38e07d31-659d-4595-939a-f18dce3446c5
      cookie_name: isso-idtoken
    system:
      discoveryurl: http://security-token-service.default.svc.nais.local/rest/v1/sts/.well-known/openid-configuration
      accepted_audience: ${tiltaksgjennomforing.audience.system}
  client:
    registration:
      kontoregister:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-fss.okonomi.sokos-kontoregister-xt/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

tiltaksgjennomforing:
  kontoregister:
    uri: https://sokos-kontoregister-xt.dev.adeo.no/kontoregister/api/v1/hent-kontonr-org
    consumer-id: ${tiltaksgjennomforing.serviceuser.username}
  database:
    database-navn: tiltaksgjennomforing-preprod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 8
    max-lifetime: 300000
  altinn-tilgangsstyring:
    uri: https://api-gw-q1.adeo.no
    proxyUri: https://arbeidsgiver.dev.intern.nav.no/altinn-rettigheter-proxy
    beOmRettighetBaseUrl: https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    ltsMidlertidigServiceCode: 5516
    ltsMidlertidigServiceEdition: 1
    ltsVarigServiceCode: 5516
    ltsVarigServiceEdition: 2
    arbtreningServiceCode: 5332
    arbtreningServiceEdition: 1
  altinn-varsel:
    uri: https://pep-gw-q1.oera-q.local:9443/ekstern/altinn/notificationagencyexternalbasic/v1
  ereg:
    uri: https://modapp-q1.adeo.no/ereg/api/v1/organisasjon
  sts:
    username: ${tiltaksgjennomforing.serviceuser.username}
    password: ${tiltaksgjennomforing.serviceuser.password}
    ws-uri: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    rest-uri: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
  axsys:
    uri: https://axsys.nais.preprod.local/api/v1/tilgang
    nav-consumer-id: ${tiltaksgjennomforing.serviceuser.username}
  abac:
    veilarbabac-uri: https://veilarbabac-q1.nais.preprod.local
  oppgave:
    oppgave-uri: https://oppgave.nais.preprod.local/api/v1/oppgaver
  unleash:
    enabled: true
    unleash-uri: https://unleash.nais.io/api/
  consumer:
    system:
      id: ${tiltaksgjennomforing.consumer.system}
  veilarbarena:
    url: https://veilarbarena-q1.nais.preprod.local/veilarbarena/api/oppfolgingsstatus
  norg2:
    url: https://app-q1.adeo.no/norg2/api/v1/enhet/navkontor/

http:
  proxy:
    parametername: nothing
