spring:
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  main:
    banner-mode: "console"

no.nav.security.oidc:
  issuers: selvbetjening, isso
  issuer:
    selvbetjening:
      discoveryurl: http://metadata-selvbetjening
      accepted_audience: aud-selvbetjening
    isso:
      discoveryurl: http://metadata-isso
      accepted_audience: aud-isso

tiltaksgjennomforing:
  altinn:
    altinn_url: http://localhost:${mock.port}/altinn
