package no.nav.tag.tiltaksgjennomforing;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class NavnGenerator {
    public static final List<String> FORNAVN = List.of(
        "Aktuell",
        "Alvorlig",
        "Ansvarlig",
        "Berømt",
        "Betydelig",
        "Bevisst",
        "Bred",
        "Dum",
        "Dyp",
        "Ekkel",
        "Eksisterende",
        "Ekte",
        "Enkel",
        "Ensom",
        "Falsk",
        "Fast",
        "Felles",
        "Fersk",
        "Fjern",
        "Flau",
        "Følsom",
        "Forsiktig",
        "Fremmed",
        "Fryktelig",
        "Glatt",
        "Gravid",
        "Grunnleggende",
        "Heldig",
        "Hemmelig",
        "Hjelpsom",
        "Hyppig",
        "Imponerende",
        "Kjedelig",
        "Kul",
        "Langsom",
        "Lat",
        "Lav",
        "Lignende",
        "Løs",
        "Lovlig",
        "Lykkelig",
        "Lys",
        "Menneskelig",
        "Merkelig",
        "Midlertidig",
        "Mistenkelig",
        "Modig",
        "Mørk",
        "Morsom",
        "Motsatt",
        "Mulig",
        "Naturlig",
        "Nåværende",
        "Nødvendig",
        "Nøyaktig",
        "Nysgjerrig",
        "Nyttig",
        "Offentlig",
        "Opprinnelig",
        "Ordentlig",
        "Plutselig",
        "Rå",
        "Rask",
        "Regelmessig",
        "Ren",
        "Rettferdig",
        "Rimelig",
        "Rund",
        "Ryddig",
        "Sannsynlig",
        "Selvsikker",
        "Sint",
        "Skarp",
        "Skikkelig",
        "Skyldig",
        "Smal",
        "Søt",
        "Spennende",
        "Stille",
        "Stolt",
        "Stram",
        "Streng",
        "Stygg",
        "Sulten",
        "Sunn",
        "Synlig",
        "Tilgjengelig",
        "Tilstrekkelig",
        "Tung",
        "Tynn",
        "Uavhengig",
        "Ujevn",
        "Ulovlig",
        "Ulykkelig",
        "Umiddelbar",
        "Urettferdig",
        "Vellykket",
        "Vennlig",
        "Verdifull",
        "Vill",
        "Villig",
        "Voksen",
        "Ærlig",
        "Åpen",
        "Åpenbar"
    );

    public static final List<String> ETTERNAVN = List.of(
        "Avstand",
        "Bakgrunn",
        "Ball",
        "Bilde",
        "Blod",
        "Bok",
        "Bokstav",
        "Bunn",
        "By",
        "Del",
        "Drøm",
        "Eksempel",
        "Eske",
        "Evne",
        "Familie",
        "Farge",
        "Feil",
        "Fest",
        "Flagg",
        "Flaske",
        "Fordel",
        "Forhold",
        "Form",
        "Forskjell",
        "Forslag",
        "Gang",
        "Grense",
        "Grunn",
        "Håp",
        "Humør",
        "Hus",
        "Idrett",
        "Jobb",
        "Kamp",
        "Kart",
        "Konge",
        "Konkurranse",
        "Kropp",
        "Lag",
        "Land",
        "Liv",
        "Lov",
        "Løype",
        "Luft",
        "Lyd",
        "Lys",
        "Mål",
        "Mat",
        "Måte",
        "Menneske",
        "Merke",
        "Miljø",
        "Møte",
        "Nøkkel",
        "Område",
        "Oppgave",
        "Ord",
        "Øyeblikk",
        "Pause",
        "Pose",
        "Pris",
        "Prøve",
        "Retning",
        "Sak",
        "Salg",
        "Samfunn",
        "Samtale",
        "Sang",
        "Seier",
        "Seng",
        "Side",
        "Situasjon",
        "Skade",
        "Skilt",
        "Skole",
        "Skritt",
        "Slutt",
        "Søvn",
        "Spill",
        "Spøk",
        "Spørsmål",
        "Sted",
        "Stemme",
        "Stjerne",
        "Støtte",
        "Stund",
        "Stykke",
        "Svar",
        "Sykdom",
        "Tall",
        "Tekst",
        "Tid",
        "Time",
        "Ting",
        "Utfordring",
        "Vær",
        "Valg",
        "Vei",
        "Venn",
        "Årsak"
    );

    public static final List<String> BEDRIFTER = Stream
        .concat(FORNAVN.stream(), ETTERNAVN.stream())
        .collect(Collectors.toList());

    public static final List<String> SELSKAPSFORM = List.of("AS", "ASA", "DA", "KF", "SA", "HF");

    public static String genererBedriftsnavn() {
        return random(BEDRIFTER) + " " + random(SELSKAPSFORM);
    }

    public static String genererFornavn() {
        return random(FORNAVN);
    }

    public static String genererEtternavn() {
        return random(ETTERNAVN);
    }

    private static String random(List<String> list) {
        return list.get((int) Math.round(Math.random() * (list.size() - 1)));
    }
}
