apiVersion: nais.io/v1
kind: Alert
metadata:
  name: tiltaksgjennomforing-api-alert
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'arbeidsgiver-tiltak-alerts'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: up{app="tiltaksgjennomforing-api", job="kubernetes-pods"} == 0
      for: 5m
      description: "tiltaksgjennomforing-api er nede"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    - alert: last ned pdf feiler
      expr: sum(increase(tiltaksgjennomforing_pdf_feil_total[15m])) > 0
      for: 15m
      description: "tiltaksgjennomforing-api feiler med pdf-generering"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    - alert: TILTAKSGJENNOMFORING-API ERROR!
      expr: sum(increase(logd_messages_total{log_app="tiltaksgjennomforing-api",log_level="Error"}[10m])) > 0
      for: 10s
      description: "tiltaksgjennomforing-api har logget en feil :this-is-fine-fire: Sjekk loggene om noe bør gjøres!"
      action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/app/r/s/HT3Nd"