apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tiltaksgjennomforing-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  groups:
    - name: tiltaksgjennomforing-api-alert
      rules:
        - alert: applikasjon nede
          expr: sum(up{app="tiltaksgjennomforing-api", job="nais-system/monitoring-apps-tenant"}) == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
          labels:
            namespace: arbeidsgiver
            severity: critical

        - alert: TILTAKSGJENNOMFORING-API ERROR!
          expr: sum(increase(logback_events_total{app="tiltaksgjennomforing-api",level="error"}[10m])) > 0
          for: 10s
          annotations:
            summary: |-
              tiltaksgjennomforing-api har logget en feil :this-is-fine-fire: Sjekk loggene om noe bør gjøres!
            action: "Sjekk logs.az.nav.no for logger: https://logs.az.nav.no/app/data-explorer/discover/#/view/f21a8b00-0cd1-11f1-b30c-21dfcb1fad46"
          labels:
            namespace: arbeidsgiver
            severity: critical
