apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api-labs
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  env:
    - name: MILJO
      value: dev-gcp-labs
    - name: FAKE_LOGIN_URI
      value: http://tiltak-fakelogin
    - name: TILTAK_REFUSJON_URI
      value: http://tiltak-refusjon-api-labs
    - name: MIN_SIDE_ARBEIDSGIVER_URI
      value: https://arbeidsgiver-q.nav.no
    - name: TILTAK_DOKGEN_URI
      value: http://tiltak-dokgen
    - name: NOTIFIKASJONER_URI
      value: https://notifikasjon-fake-produsent-api.labs.nais.io
    - name: NOTIFIKASJONER_LENKE
      value: https://arbeidsgiver.labs.nais.io
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: team_logs
        - id: loki
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing-labs
    outbound:
      rules:
        - application: tiltak-fakelogin
        - application: tiltak-refusjon-api-labs
        - application: tiltak-dokgen
