apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api
  namespace: team-tiltak
  labels:
    team: team-tiltak
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        groups:
          - id: fbfea82d-13da-43ad-a2f2-d7f21cb95f12
        extra:
          - "NAVident"
  kafka:
    pool: nav-dev
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  liveness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  leaderElection: true
  strategy:
    type: RollingUpdate
  tokenx:
    enabled: true
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing
          namespace: arbeidsgiver
          cluster: dev-gcp
        - application: min-side-arbeidsgiver
          namespace: fager
          cluster: dev-gcp
    outbound:
      rules:
        - application: tiltak-proxy
          namespace: arbeidsgiver
          cluster: dev-fss
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: tiltaksgjennomforing-api-db
            envVarPrefix: DB