apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api-q0
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  env:
    - name: MILJO
      value: dev-fss-q0
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=80.0"
  image: {{image}}
  port: 8080
  kafka:
    pool: nav-dev
  replicas:
    min: 1
    max: 1
  liveness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  resources:
    limits:
      cpu: 2000m
      memory: 12000Mi
    requests:
      cpu: 500m
      memory: 6000Mi
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus
  accessPolicy:
    outbound:
      rules:
        - application: tiltaksgjennomforing-wiremock-q0
