apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  {{#unless labs}}
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  kafka:
    pool: {{kafka-pool}}
  {{/unless}}
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  {{#if labs }}
  replicas:
    min: 1
    max: 1
  {{/if}}
  liveness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  {{#if ingress}}
  ingresses:
    - {{ingress}}
  {{/if}}
  {{#unless labs}}
  leaderElection: true
  vault:
    enabled: true
  webproxy: true
  strategy:
    type: RollingUpdate
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  {{/unless}}
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus
  {{#if labs}}
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing
        - application: tiltak-proxy
    outbound:
      rules:
        - application: tiltak-fakelogin
        - application: tiltaksgjennomforing-wiremock
        - application: tiltak-refusjon-api
        - application: tiltak-dokgen
  {{/if}}
  {{#unless labs}}
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-proxy
  {{/unless}}
  envFrom:
    - configmap: loginservice-idporten