apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  env:
    - name: MILJO
      value: prod-fss
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=80.0"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        groups:
          # Beslutter-gruppe
          - id: 156f4f79-6909-4be1-8045-323f55590898
          # Fortrolig adresse gruppe
          - id: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
          # Strengt fortrolig adresse gruppe
          - id: ad7b87a6-9180-467c-affc-20a566b0fec0
        extra:
          - "NAVident"
  kafka:
    pool: nav-prod
  image: {{image}}
  port: 8080
  liveness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /tiltaksgjennomforing-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  replicas:
    min: 3
  resources:
    limits:
      cpu: 2000m
      memory: 12000Mi
    requests:
      cpu: 500m
      memory: 6000Mi
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/tiltaksgjennomforing-api/
  vault:
    enabled: true
  webproxy: true
  strategy:
    type: RollingUpdate
  tokenx:
    enabled: true
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: team_logs
        - id: loki
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-proxy
        - application: min-side-arbeidsgiver
          namespace: fager
          cluster: prod-gcp
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
        - application: pdl-api
          namespace: pdl
      external:
        - host: team-tiltak-unleash-api.nav.cloud.nais.io
  envFrom:
    - configmap: loginservice-idporten
    - secret: tiltaksgjennomforing-api-unleash-api-token
