apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-tiltaksgjennomforing-refusjon
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  pool: nav-dev
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: arbeidsgiver
      application: tiltaksgjennomforing-api
      access: readwrite   # read, write, readwrite
    - team: arbeidsgiver
      application: tiltak-refusjon-api
      access: readwrite