apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltaksgjennomforing-wiremock-q0
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image:  ghcr.io/navikt/tiltaksgjennomforing-api/wiremock:2.27.2
  replicas:
    min: 2
    max: 4
  port: 8080
  liveness:
    path: /ereg/912345678
    initialDelay: 1
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /ereg/912345678
    initialDelay: 1
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      cpu: 1000m
      memory: 4000Mi
    requests:
      cpu: 500m
      memory: 2000Mi
  env:
  - name: deploytrigger
    value: "{{deploytrigger}}"
  filesFrom:
  - configmap: tiltaksgjennomforing-wiremock-q0
    mountPath: /home/wiremock/mappings
  accessPolicy:
    inbound:
      rules:
      - application: tiltaksgjennomforing-api-q0
