apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: tiltaksgjennomforing-wiremock
  name: tiltaksgjennomforing-wiremock
  namespace: arbeidsgiver
data:
  altinn_tilgangsstyring.json: |
    {
      "mappings": [
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^1\\d{10}$"
              },
              "serviceCode": {
                "equalTo": "5332"
              },
              "serviceEdition": {
                "equalTo": "1"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "[{\"Name\":\"Saltrød og Høneby\",\"Type\":\"Business\",\"OrganizationNumber\":\"999999999\",\"OrganizationForm\":\"BEDR\",\"Status\":\"Active\"}]",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^2[0-5]\\d{9}$"
              },
              "serviceCode": {
                "equalTo": "5332"
              },
              "serviceEdition": {
                "equalTo": "1"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "[{\"Name\":\"SOPRA STERIA AS\",\"Type\":\"Business\",\"OrganizationNumber\":\"910909088\",\"OrganizationForm\":\"BEDR\",\"Status\":\"Active\"}, {\"Name\":\"KIWI LØREN AS\",\"Type\":\"Business\",\"OrganizationNumber\":\"981121465\",\"OrganizationForm\":\"BEDR\",\"Status\":\"Active\"}]",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^26\\d{9}$"
              },
              "serviceCode": {
                "equalTo": "5516"
              },
              "serviceEdition": {
                "equalTo": "1"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "[{\"Name\":\"HUNNDALEN OG NEVERDAL\",\"Type\":\"Business\",\"OrganizationNumber\":\"910712306\",\"OrganizationForm\":\"BEDR\",\"Status\":\"Active\"}]",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^27\\d{9}$"
              },
              "serviceCode": {
                "equalTo": "5516"
              },
              "serviceEdition": {
                "equalTo": "2"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "[{\"Name\":\"BIRTAVARRE OG VÆRLANDET REGNSKAP\",\"Type\":\"Business\",\"OrganizationNumber\":\"910825607\",\"OrganizationForm\":\"BEDR\",\"Status\":\"Active\"}]",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^31\\d{9}$"
              },
              "serviceCode": {
                "equalTo": "5332"
              },
              "serviceEdition": {
                "equalTo": "1"
              }
            }
          },
          "response": {
            "status": 500,
            "headers": {
              "Content-Type": "application/json"
            },
            "statusMessage": "Internal Server Error: 500 UserID"
          }
        },
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^1\\d{10}$"
              },
              "serviceCode": {
                "equalTo": "5516"
              },
              "serviceEdition": {
                "equalTo": "1"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "[{\"Name\":\"Bedriften Med Midlertidi Lts\",\"Type\":\"Business\",\"OrganizationNumber\":\"910712314\",\"OrganizationForm\":\"BEDR\",\"Status\":\"Active\"}]",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^1\\d{10}$"
              },
              "serviceCode": {
                "equalTo": "5516"
              },
              "serviceEdition": {
                "equalTo": "2"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "[{\"Name\":\"Bedriften Med Varig Lts\",\"Type\":\"Business\",\"OrganizationNumber\":\"910712306\",\"OrganizationForm\":\"BEDR\",\"Status\":\"Active\"}]",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^30\\d{9}$"
              },
              "serviceCode": {
                "matches": "5516|5332"
              },
              "serviceEdition": {
                "matches": "1|2"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "[{\"Name\":\"Bedriften Med Alle Rettigheter\",\"Type\":\"Business\",\"OrganizationNumber\":\"910825607\",\"OrganizationForm\":\"BEDR\",\"Status\":\"Active\"}]",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 2,
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "matches" : "^\\d{11}$"
              },
              "serviceCode": {
                "matches": "5332|5516"
              },
              "serviceEdition": {
                "matches": "1|2"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "[]",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "request": {
            "method": "GET",
            "urlPath": "/altinn-tilgangsstyring",
            "queryParameters" : {
              "subject" : {
                "doesNotMatch" : "^\\d{11}$"
              }
            }
          },
          "response": {
            "status": 400,
            "headers": {
              "Content-Type": "application/json"
            },
            "statusMessage": "Invalid social security number"
          }
        }
      ]
    }
  altinn_varsel.json: |
    {
      "mappings": [
        {
          "request": {
            "method": "POST",
            "urlPath": "/altinn-varsel"
          },
          "response": {
            "status": 200,
            "body": "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns=\"http://www.altinn.no/services/ServiceEngine/Notification/2010/10\" xmlns:ns1=\"http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06\"><soapenv:Header/><soapenv:Body><ns:SendStandaloneNotificationBasicV3Response><ns:SendStandaloneNotificationBasicV3Result></ns:SendStandaloneNotificationBasicV3Result></ns:SendStandaloneNotificationBasicV3Response></soapenv:Body></soapenv:Envelope>",
            "headers": {
              "Content-Type": "application/soap+xml"
            }
          }
        }
      ]
    }
  axsys.json: |
    {
      "mappings": [
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPath": "/axsys/X123456",
            "queryParameters" : {
              "inkluderAlleEnheter": {
                "equalTo": "false"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "{\"enheter\":[{\"enhetId\":\"0906\",\"fagomrader\":[\"ABC\",\"DEF\",\"GHI\",\"JKL\",\"MNO\",\"PQR\",\"STU\",\"WXY\"],\"navn\":\"NAV Storebyen\"},{\"enhetId\":\"0904\",\"fagomrader\":[\"ABC\",\"DEF\",\"GHI\",\"JKL\",\"MNO\",\"PQR\",\"STU\",\"WXY\"],\"navn\":\"NAV Lillebyen\"}]}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 2,
          "request": {
            "method": "GET",
            "urlPathPattern": "/axsys/[A-Z]{1}[0-9]{6}",
            "queryParameters": {
              "inkluderAlleEnheter": {
                "equalTo": "false"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "{\"enheter\": []}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        }
      ]
    }
  ereg.json: |
    {
      "mappings": [
        {
          "request": {
            "method": "GET",
            "urlPattern": "/ereg/9[0-9]{8}"
          },
          "response": {
            "status": 200,
            "body": "{\"organisasjonsnummer\":\"999999999\",\"type\":\"Virksomhet\",\"navn\":{\"navnelinje1\":\"Saltrød og\",\"navnelinje4\":\"Høneby\",\"bruksperiode\":{\"fom\":\"2019-01-14T11:39:39.512\"},\"gyldighetsperiode\":{\"fom\":\"2018-10-28\"}},\"organisasjonDetaljer\":{\"registreringsdato\":\"2018-10-28T00:00:00\",\"enhetstyper\":[{\"enhetstype\":\"BEDR\",\"bruksperiode\":{\"fom\":\"2019-01-14T11:39:39.511\"},\"gyldighetsperiode\":{\"fom\":\"2019-01-14\"}}],\"navn\":[{\"navnelinje1\":\"Saltrød og Høneby\",\"bruksperiode\":{\"fom\":\"2019-01-14T11:39:39.512\"},\"gyldighetsperiode\":{\"fom\":\"2018-10-28\"}}],\"forretningsadresser\":[{\"adresselinje1\":\"Nedre Tyholms vei13, 4836 Arendal\",\"adresselinje3\":\"Nedre Tyholms vei 13, 4836 Arendal\",\"postnummer\":\"4836\",\"landkode\":\"NO\",\"kommunenummer\":\"0906\",\"bruksperiode\":{\"fom\":\"2019-01-14T11:39:39.512\"},\"gyldighetsperiode\":{\"fom\":\"2018-10-28\"}}],\"postadresser\":[{\"adresselinje1\":\"Postboks 502 Lund,4605 KRISTIANSAN\",\"adresselinje2\":\"DS\",\"adresselinje3\":\"Postboks 502 Lund,4605 KRISTIANSA\",\"postnummer\":\"4605\",\"landkode\":\"NO\",\"kommunenummer\":\"1001\",\"bruksperiode\":{\"fom\":\"2019-01-14T11:39:39.512\"},\"gyldighetsperiode\":{\"fom\":\"2018-10-28\"}}],\"sistEndret\":\"2018-10-28\"},\"virksomhetDetaljer\":{\"enhetstype\":\"BEDR\"}}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        }
      ]
    }
  pdl_gradering.json: |
    {
      "mappings": [
        {
          "request": {
            "method": "POST",
            "urlPath": "/persondata"
          },
          "response": {
            "status": 200,
            "body": "{\"errors\": [{\"message\": \"Fant ikke person\", \"locations\": [{\"line\": 1, \"column\": 8}], \"path\": [\"hentPerson\"], \"extensions\": {\"code\": \"not_found\", \"classification\": \"ExecutionAborted\"}}], \"data\": {\"hentPerson\": null}}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "request": {
            "method": "POST",
            "urlPath": "/persondata",
            "headers": {
              "Content-Type": {
                "equalTo": "application/json",
                "caseInsensitive": true
              }
            },
            "bodyPatterns" : [ {
              "equalToJson" : {"query" : "query($ident: ID!) { hentPerson(ident: $ident) { adressebeskyttelse { gradering } } }", "variables":  {"ident": "16053900422"}}
            } ]
          },
          "response": {
            "status": 200,
            "body": "{\"data\": {\"hentPerson\": {\"adressebeskyttelse\": [{\"gradering\": \"STRENGT_FORTROLIG\"}]}}}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "request": {
            "method": "POST",
            "urlPath": "/persondata",
            "headers": {
              "Content-Type": {
                "equalTo": "application/json",
                "caseInsensitive": true
              }
            },
            "bodyPatterns" : [ {
              "equalToJson" : {"query" : "query($ident: ID!) { hentPerson(ident: $ident) { adressebeskyttelse { gradering } } }", "variables":  {"ident": "28033114267"}}
            } ]
          },
          "response": {
            "status": 200,
            "body": "{\"data\": {\"hentPerson\": {\"adressebeskyttelse\": [{\"gradering\": \"STRENGT_FORTROLIG_UTLAND\"}]}}}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "request": {
            "method": "POST",
            "urlPath": "/persondata",
            "headers": {
              "Content-Type": {
                "equalTo": "application/json",
                "caseInsensitive": true
              }
            },
            "bodyPatterns" : [ {
              "equalToJson" : {"query" : "query($ident: ID!) { hentPerson(ident: $ident) { adressebeskyttelse { gradering } } }", "variables":  {"ident": "00000000000"}}
            } ]
          },
          "response": {
            "status": 200,
            "body": "{\"data\": {\"hentPerson\": {\"adressebeskyttelse\": [{\"gradering\": \"UGRADERT\"}]}}}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "request": {
            "method": "POST",
            "urlPath": "/persondata",
            "headers": {
              "Content-Type": {
                "equalTo": "application/json",
                "caseInsensitive": true
              }
            },
            "bodyPatterns" : [ {
              "equalToJson" : {"query" : "query($ident: ID!) { hentPerson(ident: $ident) { adressebeskyttelse { gradering } } }", "variables":  {"ident": "26067114433"}}
            } ]
          },
          "response": {
            "status": 200,
            "body": "{\"data\": {\"hentPerson\": {\"adressebeskyttelse\": [{\"gradering\": \"FORTROLIG\"}]}}}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "request": {
            "method": "POST",
            "urlPath": "/persondata",
            "headers": {
              "Content-Type": {
                "equalTo": "application/json",
                "caseInsensitive": true
              }
            },
            "bodyPatterns" : [ {
              "equalToJson" : {"query" : "query($ident: ID!) { hentPerson(ident: $ident) { adressebeskyttelse { gradering } } }", "variables":  {"ident": "18076641842"}}
            } ]
          },
          "response": {
            "status": 200,
            "body": "{\"data\": {\"hentPerson\": {\"adressebeskyttelse\": [{\"gradering\": \"\"}]}}}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "request": {
            "method": "POST",
            "urlPath": "/persondata",
            "headers": {
              "Content-Type": {
                "equalTo": "application/json",
                "caseInsensitive": true
              }
            },
            "bodyPatterns" : [ {
              "equalToJson" : {"query" : "query($ident: ID!) { hentPerson(ident: $ident) { adressebeskyttelse { gradering } } }", "variables":  {"ident": "23097010706"}}
            } ]
          },
          "response": {
            "status": 200,
            "body": "{\"errors\": [{\"message\": \"Fant ikke person\", \"locations\": [{\"line\": 1, \"column\": 8}], \"path\": [\"hentPerson\"], \"extensions\": {\"code\": \"not_found\", \"classification\": \"ExecutionAborted\"}}]}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "request": {
            "method": "POST",
            "urlPath": "/persondata",
            "headers": {
              "Content-Type": {
                "equalTo": "application/json",
                "caseInsensitive": true
              }
            },
            "bodyPatterns" : [ {
              "equalToJson" : {"query" : "query($ident: ID!) { hentPerson(ident: $ident) { navn { fornavn mellomnavn etternavn } } }", "variables":  {"ident": "00000000000"}}
            } ]
          },
          "response": {
            "status": 200,
            "body": "{\"data\": {\"hentPerson\": {\"navn\": [{\"fornavn\": \"Donald\", \"etternavn\": \"Duck\"}]}}}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        }
      ]
    }
  sts.json: |
    {
      "mappings": [
        {
          "request": {
            "method": "GET",
            "urlPattern": "/sts/sts/token.*"
          },
          "response": {
            "status": 200,
            "body": "{\"access_token\":\"fdg\",\"token_type\":\"asfsdg\",\"expires_in\":325}",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        }
      ]
    }
  veilarbabac.json: |
    {
      "mappings": [
        {
          "priority": 1,
          "request": {
            "method": "GET",
            "urlPattern": "/veilarbabac/person.*",
            "queryParameters" : {
              "fnr" : {
                "matches" : "^1\\d{10}$"
              }
            }
          },
          "response": {
            "status": 200,
            "body": "deny",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "priority": 2,
          "request": {
            "method": "GET",
            "urlPattern": "/veilarbabac/person.*"
          },
          "response": {
            "status": 200,
            "body": "permit",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        }
      ]
    }
