-- Oppdater avtale_innhold...
alter table avtale_innhold alter column antall_dager_per_uke type numeric using antall_dager_per_uke::numeric;
alter table avtale_innhold alter column stillingprosent type numeric using stillingprosent::numeric;
-- Og arena-tabellene...
alter table arena_tiltakdeltaker alter column prosent_deltid type text using prosent_deltid::text;
alter table arena_tiltakgjennomforing alter column prosent_deltid type text using prosent_deltid::text;
