create table avtale_innhold as
select id,
       id as avtale,
       deltaker_fornavn,
       deltaker_etternavn,
       deltaker_tlf,
       bedrift_navn,
       arbeidsgiver_fornavn,
       arbeidsgiver_etternavn,
       arbeidsgiver_tlf,
       veileder_fornavn,
       veileder_etternavn,
       veileder_tlf,
       oppfolging,
       tilrettelegging,
       start_dato,
       slutt_dato,
       stillingprosent,
       journalpost_id,
       godkjent_av_deltaker,
       godkjent_av_arbeidsgiver,
       godkjent_av_veileder,
       godkjent_pa_vegne_av,
       ikke_bank_id,
       reservert,
       digital_kompetanse,
       arbeidsgiver_kontonummer,
       stillingtype,
       stillingbeskrivelse,
       lonnstilskudd_prosent,
       manedslonn,
       feriepengesats,
       arbeidsgiveravgift
from avtale;

alter table avtale drop column
    deltaker_fornavn,
    deltaker_etternavn,
    deltaker_tlf,
    bedrift_navn,
    arbeidsgiver_fornavn,
    arbeidsgiver_etternavn,
    arbeidsgiver_tlf,
    veileder_fornavn,
    veileder_etternavn,
    veileder_tlf,
    oppfolging,
    tilrettelegging,
    start_dato,
    slutt_dato,
    stillingprosent,
    journalpost_id,
    godkjent_av_deltaker,
    godkjent_av_arbeidsgiver,
    godkjent_av_veileder,
    godkjent_pa_vegne_av,
    ikke_bank_id,
    reservert,
    digital_kompetanse,
    arbeidsgiver_kontonummer,
    stillingtype,
    stillingbeskrivelse,
    lonnstilskudd_prosent,
    manedslonn,
    feriepengesats,
    arbeidsgiveravgift;

alter table maal rename column avtale to avtale_innhold;
alter table oppgave rename column avtale to avtale_innhold;