CREATE TABLE avtale (
  id serial primary key,
  opprettet_tidspunkt timestamp without time zone not null default now(),

  deltaker_fornavn varchar(255),
  deltaker_etternavn varchar(255),
  deltaker_adresse varchar(255),
  deltaker_postnummer varchar(255),
  deltaker_poststed varchar(255),

  bedrift_navn varchar(255),
  bedrift_adresse varchar(255),
  bedrift_postnummer varchar(255),
  bedrift_poststed varchar(255),

  arbeidsgiver_fornavn varchar(255),
  arbeidsgiver_etternavn varchar(255),
  arbeidsgiver_epost varchar(255),
  arbeidsgiver_tlf varchar(255),

  veileder_fornavn varchar(255),
  veileder_etternavn varchar(255),
  veileder_epost varchar(255),
  veileder_tlf varchar(255),

  oppfolging varchar(255),
  tilrettelegging varchar(255),

  start_dato_timestamp timestamp without time zone,
  arbeidstrening_lengde integer,
  arbeidstrening_stillingprosent integer,

  bekreftet_av_bruker boolean,
  bekreftet_av_arbeidsgiver boolean,
  bekreftet_av_veileder boolean,
);

insert into AVTALE (
  deltaker_fornavn,
  deltaker_etternavn,
  deltaker_adresse,
  deltaker_postnummer,
  deltaker_poststed,
  bedrift_navn,
  bedrift_adresse,
  bedrift_postnummer,
  bedrift_poststed,
  arbeidsgiver_fornavn,
  arbeidsgiver_etternavn,
  arbeidsgiver_epost,
  arbeidsgiver_tlf,
  veileder_fornavn,
  veileder_etternavn,
  veileder_epost,
  veileder_tlf,
  oppfolging,
  tilrettelegging,
  start_dato_timestamp,
  arbeidstrening_lengde,
  arbeidstrening_stillingprosent,
  bekreftet_av_bruker,
  bekreftet_av_arbeidsgiver,
  bekreftet_av_veileder,
) values (
  'Donald',
  'Duck',
  'Duck',
  'Donald',
  'Duck',
  'Duck',
  'Donald',
  'Duck',
  'Duck',
  'Duck',
  'Duck',
  'Duck',
  'Donald',
  'Duck',
  'Duck',
  'Donald',
  'Duck',
  'Duck',
  'Duck',
  '2018-01-10',
  12,
  60,
  false,
  true,
  false,
);
