ALTER TABLE avtale ALTER COLUMN id TYPE VARCHAR(255);

ALTER TABLE maal ALTER COLUMN id TYPE VARCHAR(255);
ALTER TABLE maal ALTER COLUMN avtale TYPE VARCHAR(255);

ALTER TABLE oppgave ALTER COLUMN id TYPE VARCHAR(255);
ALTER TABLE oppgave ALTER COLUMN avtale TYPE VARCHAR(255);
