ALTER TABLE avtale ALTER COLUMN id TYPE UUID;

ALTER TABLE maal ALTER COLUMN id TYPE UUID;
ALTER TABLE maal ALTER COLUMN avtale TYPE UUID;

ALTER TABLE oppgave ALTER COLUMN id TYPE UUID;
ALTER TABLE oppgave ALTER COLUMN avtale TYPE UUID;
