package no.nav.tag.tiltaksgjennomforing.exceptions;

public enum Feilkode {
    ALT_MA_VAERE_FYLT_UT,
    ARBEIDSGIVER_SKAL_GODKJENNE_FOER_VEILEDER,
    DELTAKER_HAR_GODKJENT,
    ER_ALLEREDE_VEILEDER,
    GODKJENT_PAA_VEGNE_GRUNN_MAA_VELGES,
    GRUNN_TIL_AVBRYTELSE,
    IKKE_VALGT_PART,
    KAN_IKKE_ENDRE,
    KAN_IKKE_LAASES_OPP,
    KAN_IKKE_OPPHEVE,
    SAMTIDIGE_ENDRINGER,
    START_ETTER_SLUTT,
    UGYLDIG_TLF,
    IKKE_AKSEPTERT_UTKAST,
    VARIGHET_FOR_LANG_MIDLERTIDIG_LONNSTILSKUDD,
    VARIGHET_FOR_LANG_ARBEIDSTRENING,
    VARIGHET_FOR_LANG_MENTOR,
    VEILEDER_SKAL_GODKJENNE_SIST,
    ALTINN_FEIL,
}
