name: Bygg og deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    name: Bygg og deploy image
    uses: ./.github/workflows/bygg.yml
    with:
      push-image: true
    secrets: inherit

  deploy-dev:
    name: Deploy til dev
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yaml,nais/unleash-apitoken.yml
          VAR: image=${{ needs.build.outputs.image }},unleash-environment=development

  deploy-prod:
    name: Deploy til prod
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Deploy til prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: nais/prod-fss.yaml,nais/alerterator.yaml,nais/unleash-apitoken.yml
          VAR: image=${{ needs.build.outputs.image }},unleash-environment=production
