name: Bygg og deploy - Q0

on:
  workflow_dispatch:

jobs:
  build:
    name: Bygg
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Oppsett Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Bygg og test med Maven
        run: mvn package -B -Dsurefire.useFile=false

      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          byosbom: target/bom.json
          team: arbeidsgiver
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-gcp-q0:
    name: Deploy til q0
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Generer tiltaksgjennomforing-wiremock configmap
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          ./kubectl create configmap --dry-run=client -o yaml --from-file src/test/resources/mappings -n arbeidsgiver tiltaksgjennomforing-wiremock-q0 > nais/wiremock-mappings-q0.yaml
          cat nais/wiremock-mappings-q0.yaml # debug

      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss-q0.yaml,nais/wiremock-q0.yaml,nais/wiremock-mappings-q0.yaml
          VAR: image=${{ needs.build.outputs.image }},deploytrigger=${{ github.run_number }}
